client.go, datasrc.go, emails.go, handlers.go, main.go, routes.go
Should satisfy #63 once finalized
=> Restructure backend code

README.md, config.go, frontend/src/components/WarriorCard.svelte, frontend/src/components/icons/WarriorRankCorporal.svelte, frontend/src/components/icons/WarriorRankGeneral.svelte, frontend/src/components/icons/WarriorRankPrivate.svelte, frontend/src/utils.css, handlers.go, pkg/database/battles.go, pkg/database/types.go
Show the warrior's rank next to the name in the battles.
Icons used per rank:
Result:
=> Show Warrior Rank

README.md, config.go, frontend/src/components/Notifications.svelte, handlers.go
The notifications are hidden way too fast for me to read them.  This pull request makes the timeouts configurable.
=> Configurable notification timeout

frontend/src/components/PointCard.svelte
Add class "select-none" for point card to disable selection text.
=> Disable selection for point card

README.md, auth.go, config.go, frontend/src/App.svelte, frontend/src/pages/Login.svelte, frontend/src/pages/WarriorProfile.svelte, handlers.go, pkg/database/warriors.go, routes.go
Thanks @eivindt for your hard work on this feature, I will bring this in so others can take advantage of it ;)
=> Ldap authentication

frontend/public/lang/default/de.json, frontend/public/lang/default/en.json, frontend/public/lang/friendly/de.json, frontend/public/lang/friendly/en.json, frontend/src/config.js
Translation into German language and a typo in the English file
=> Language file for German

README.md, auth.go, build/rollup.config.js, config.go, frontend/public/index.html, frontend/src/App.svelte, frontend/src/apiclient.js, frontend/src/config.js, frontend/src/i18n.js, frontend/src/pages/Battle.svelte, frontend/src/stores.js, handlers.go, main.go, pkg/email/email.go, pkg/email/users.go, routes.go
This resolves #100 by allowing configurable path prefix
=> Add Path Prefix support

frontend/public/lang/default/ru.json, frontend/public/lang/friendly/ru.json
I translated the missing phrases and also translated the "friendly verbs" for Russian translation
=> Translate missing phrases to Russian

client.go, handlers.go, pkg/database/plans.go, pkg/database/warriors.go, pkg/email/email.go, pkg/email/email_test.go, utils_test.go
It commit removes unnecessary comparisons for bool variables with "true" or "false".
=> Remove equality comparison for bool

frontend/src/components/InviteWarrior.svelte
=> PathPrefix has already been added to the appRoutes.<member>

auth.go
=> Fix error on first ldap login

frontend/public/lang/de.json, frontend/public/lang/en.json, frontend/public/lang/es.json, frontend/public/lang/fr.json, frontend/public/lang/pt.json, frontend/public/lang/ru.json, frontend/src/App.svelte, frontend/src/components/LocaleSwitcher.svelte, frontend/src/config.js, frontend/src/pages/Login.svelte, frontend/src/pages/WarriorProfile.svelte, handlers_user.go, pkg/database/types.go, pkg/database/users.go, schema.sql
- add locale selector to the warrior profile
- use user's locale when loading the app (either from cookie or after user logged in)
- locale "en" is used as default
=> Add user preference for locale #175

api/battle.go, api/middleware.go, api/retro.go, api/storyboard.go, api/util.go, config.go, db/battles.go, db/migrations/20220807131727_add_team_create_battle_retro_storyboard.down.sql, db/migrations/20220807131727_add_team_create_battle_retro_storyboard.up.sql, db/retro.go, db/storyboards.go, docs/CONFIGURATION.md, e2e/tests/api/battles.spec.ts, e2e/tests/api/retros.spec.ts, e2e/tests/api/storyboards.spec.ts, frontend/public/lang/de.json, frontend/public/lang/en.json, frontend/public/lang/es.json, frontend/public/lang/fr.json, frontend/public/lang/pt.json, frontend/public/lang/ru.json, frontend/src/components/battle/CreateBattle.svelte, frontend/src/components/retro/CreateRetro.svelte, frontend/src/components/storyboard/CreateStoryboard.svelte, http.go
=> Add configurable team required for creation of battles, retros or storyboards

config.go, frontend/src/components/battle/VoteResults.svelte, frontend/src/pages/Battle.svelte
We recently found this tool and find it very useful 🎉 
Although we are relying on Fibonacci deck and use Coffee card, so would appreciate if you will allow this change.
=> Add support for deck with Fibonacci numbers, add Coffee card

frontend/src/pages/Retro.svelte
=> Allow anyone to add action items in retro

api/battle.go, api/battle/events.go, db/battles.go, db/migrations/20230305023636_add_poker_hide_voter_identity_option.down.sql, db/migrations/20230305023636_add_poker_hide_voter_identity_option.up.sql, frontend/src/components/battle/CreateBattle.svelte, frontend/src/components/battle/EditBattle.svelte, frontend/src/components/battle/PointCard.svelte, frontend/src/components/battle/VoteResults.svelte, frontend/src/pages/Battle.svelte, model/battle.go
=> Add poker option to hide voter identity

frontend/src/components/battle/BattlePlans.svelte, frontend/src/components/battle/CsvImport.svelte, frontend/src/components/battle/ImportModal.svelte, frontend/src/components/battle/JiraImport.svelte, frontend/src/i18n/de/index.ts, frontend/src/i18n/en/index.ts, frontend/src/i18n/es/index.ts, frontend/src/i18n/fa/index.ts, frontend/src/i18n/fr/index.ts, frontend/src/i18n/i18n-types.ts, frontend/src/i18n/it/index.ts, frontend/src/i18n/pt/index.ts, frontend/src/i18n/ru/index.ts
Better UX and ability to keep adding import sources
=> Move import plan buttons to modal

frontend/src/components/storyboard/GoalEstimate.svelte, frontend/src/pages/Storyboard.svelte
=> Add storyboard goal estimate

docker-compose.yml
this update has 2 security patches.
here is the release: https://github.com/maildev/maildev/releases/tag/v2.1.0
=> Update mail-dev image

db/retro/retro.go, docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, email/retro.go, http/http.go, http/retro/events.go, http/retro/retro.go, thunderdome/email.go, thunderdome/retro.go
=> Add retro completed email

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, go.mod, go.sum, internal/atlassian/jira/client.go, internal/atlassian/jira/stories.go, internal/atlassian/jira/types.go, internal/db/jira/instance.go, internal/db/jira/jira.go, internal/db/migrations/20230930180117_add_jira_tables.sql, internal/db/subscription/subscription.go, internal/db/user/user.go, internal/http/http.go, internal/http/jira.go, internal/http/middleware.go, internal/http/types.go, main.go, thunderdome/jira.go, thunderdome/user.go, ui/src/components/Modal.svelte, ui/src/components/TextInput.svelte, ui/src/components/jira/CreateJiraInstance.svelte, ui/src/components/poker/ImportModal.svelte, ui/src/components/poker/PokerStories.svelte, ui/src/pages/poker/PokerGame.svelte, ui/src/pages/subscription/Confirmation.svelte, ui/src/pages/user/UserProfile.svelte
=> Jira integration

ui/src/pages/poker/PokerGame.svelte, ui/src/pages/retro/Retro.svelte, ui/src/pages/storyboard/Storyboard.svelte, ui/src/pages/user/Register.svelte
=> Hide guest registration if disabled

internal/config/config.go, internal/config/types.go, internal/http/checkin/checkin.go, internal/http/checkin/client.go, internal/http/checkin/hub.go, internal/http/http.go, internal/http/poker/client.go, internal/http/poker/hub.go, internal/http/poker/poker.go, internal/http/retro/client.go, internal/http/retro/hub.go, internal/http/retro/retro.go, internal/http/storyboard/client.go, internal/http/storyboard/hub.go, internal/http/storyboard/storyboard.go, internal/http/types.go, main.go
=> Allow configuration of websocket ping pong and write wait seconds

internal/db/retro/retro.go, internal/db/storyboard/storyboard.go, internal/http/retro.go, internal/http/storyboard.go, thunderdome/retro.go, thunderdome/storyboard.go, ui/src/pages/retro/Retros.svelte, ui/src/pages/storyboard/Storyboards.svelte
Add pagination to My Retros and My Storyboards pages, also refactor list queries for performance improvement.
Visit My Retros page with at least 11 Retros, scroll to bottom to find and use pagination
Visit My Storyboards page with at least 11 Storyboards, scroll to bottom to find and use pagination
=> Add pagination to retro and storyboard pages

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/db/migrations/20240329084022_update_retro_table.sql, internal/db/retro/retro.go, internal/http/retro/events.go, internal/http/retro/retro.go, thunderdome/retro.go, ui/src/components/retro/InviteUser.svelte, ui/src/components/retro/UserCard.svelte, ui/src/pages/retro/Retro.svelte
Adds user ready status to Retro phase
Resolves #506
Go to Retro Brainstorming phase, click the Thumbs Up below your name to mark yourself as done brainstorming/ready for next phase.  Click again if you need to unmark your done status.
=> Retro add user ready status

docs/CODE_OF_CONDUCT.md, docs/CONFIGURATION.md, docs/CONTRIBUTING.md, docs/DEVELOPING.md
This PR updates the Configuration and Contributing documentations.
=> Update configuration and contributing documentation

ui/src/components/jira/JQLImport.svelte, ui/src/components/poker/ImportModal.svelte, ui/src/components/poker/PokerStories.svelte, ui/src/components/poker/StoryFromGameImport.svelte, ui/src/pages/poker/PokerGame.svelte, ui/src/pages/subscription/Pricing.svelte
Add premium feature for importing story from another game to poker feature.
Resolves #199 
1. With an active subscription (or self hosted with subscriptions disabled) go to a poker game
2. Click import stories
3. Click import from another game
4. Select another game
5. Click import on stories to import
=> Poker import story another game

ui/src/components/poker/ImportModal.svelte, ui/src/components/poker/StoryFromStoryboardImport.svelte, ui/src/pages/subscription/Pricing.svelte
This PR adds import story from storyboard to poker game.
This feature requires a Subscription (except when subscriptions are disabled on self-hosted instances)
This resolves #432
Selfhosted or Subscription required
1. Go to a poker game
2. Click import stories
3. Click import from a storyboard
4. Select a storyboard
5. Select a goal from storyboard
6. Click "Import" on respective stories to import
=> Add import story from storyboard to poker game

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/db/team/metrics.go, internal/http/http.go, internal/http/organization.go, internal/http/team.go, thunderdome/organization.go, thunderdome/team.go, ui/src/components/global/MetricsDisplay.svelte, ui/src/components/team/metrics.ts, ui/src/pages/admin/Admin.svelte, ui/src/pages/team/Organization.svelte
This PR adds a nice display of organization metrics to the organization page, giving a quick overview of the organization to its members.
=> Add metrics display on organization page

e2e/tests/poker-game.spec.ts, ui/package-lock.json, ui/package.json, ui/src/components/poker/VotingMetrics.svelte, ui/src/pages/poker/PokerGame.svelte
This PR redesigns the poker voting results feature to be more useful for teams to quickly grasp what the results of the voting were as well as help guide them on consensus.
=> Redesign the poker voting results

ui/src/components/global/FullpageLoader.svelte, ui/src/components/global/JoinCodeForm.svelte, ui/src/pages/poker/PokerGame.svelte, ui/src/pages/retro/Retro.svelte, ui/src/pages/storyboard/Storyboard.svelte
Redesign the loading and reloading states of webscoket pages (poker, retro, storyboard) to be less visually abrupt especially for socket reconnecting states.  Also same sort of visual adjustment to the Join passcode required flow for the same pages.
1. Visit a retro, storyboard, or poker game and observe the loading and reloading screens
2. Visit one of those pages with a set join passcode as a user not yet joined
=> Redesign the loading and reloading states of webscoket pages

internal/config/config.go, internal/config/types.go, internal/http/checkin/checkin.go, internal/http/checkin/client.go, internal/http/http.go, internal/http/poker/client.go, internal/http/poker/poker.go, internal/http/retro/client.go, internal/http/retro/retro.go, internal/http/storyboard/client.go, internal/http/storyboard/storyboard.go, internal/http/types.go, main.go, thunderdome/app.go, ui/src/pages/poker/PokerGame.svelte, ui/src/pages/retro/Retro.svelte, ui/src/pages/storyboard/Storyboard.svelte, ui/src/pages/team/TeamCheckin.svelte, ui/src/websocketUtil.ts
Add support for routing websockets through a subdomain, for the purposes of infrastructure needs.
=> Add support for routing websockets through a subdomain

ui/src/components/retro/BrainstormPhase.svelte, ui/src/components/retro/GroupPhase.svelte, ui/src/components/retro/GroupedItems.svelte, ui/src/components/retro/ItemComments.svelte, ui/src/components/retro/ItemForm.svelte, ui/src/components/retro/RetroFeedbackGroup.svelte, ui/src/components/retro/RetroFeedbackItem.svelte, ui/src/components/retro/VotePhase.svelte, ui/src/pages/retro/Retro.svelte
Redesign the retro UI in effort to make feedback groups and items more visually cohesive with additional room for functionality such as displaying a tag for the feedback type after the brainstorm phase to provide the context of the feedback.
This resolves #618
=> Redesign the retro UI

ui/src/components/user/CreateUser.svelte, ui/src/components/user/UserRegisterForm.svelte
Resvolves #665 by fixing admin not able to create user in UI when registration is disabled
#665
=> Fix for #665 registration disabled admin user create

e2e/package-lock.json
=> update e2e dependencies

internal/db/user/user.go
The LDAP authentication checks if an LDAP user already exists by querying its database for a user with a specific e-mail address, and if so, returns the user straight from the database.
Prior to this commit, only a select few database columns were returned, resulting in a response to the UI containing a bunch of nil/empty strings, which in turn made the UI save an empty string in localStorage.
Now, the GetUserByID & GetUserByEmail database queries select the same columns, which should prevent the issue.
I tested this locally by adding a `GetUserByEmail` call to `handleLogin`, so I wouldn't have to setup LDAP locally.
=> Fix user theme breakage when using LDAP auth

docs/CONFIGURATION.md, docs/INSTALLATION.md, internal/config/config.go, internal/config/types.go, internal/cookie/auth.go, internal/cookie/cookie.go, internal/cookie/user.go, internal/db/auth/oauth.go, internal/http/http.go, internal/http/organization.go, internal/http/team.go, internal/http/types.go, internal/oauth/oauth.go, internal/oauth/type.go, main.go, thunderdome/app.go, ui/src/components/auth/LoginForm.svelte, ui/src/i18n/en/index.ts, ui/src/i18n/i18n-types.ts, ui/src/pages/user/Login.svelte
Add SSO OpenID Connect provider support.
TODO:
=> Add SSO OpenID Connect provider support

docs/CONFIGURATION.md, internal/http/http.go
Add the path prefix to SSL enabled oidc callback URL
See #682 
none
* enable OIDC behind an SSL enabled instance
* Configure path prefix
* Attempt to log in with SSO
=> (iss #682) OIDC

e2e/package-lock.json, e2e/package.json, e2e/tests/admin/admin.spec.ts, e2e/tests/admin/alerts.spec.ts, e2e/tests/admin/apikeys.spec.ts, e2e/tests/admin/department.spec.ts, e2e/tests/admin/organization.spec.ts, e2e/tests/admin/organizations.spec.ts, e2e/tests/admin/poker-games.spec.ts, e2e/tests/admin/team.spec.ts, e2e/tests/admin/teams.spec.ts, e2e/tests/admin/users.spec.ts, e2e/tests/landing.spec.ts, e2e/tests/user/profile.spec.ts, ui/src/pages/Landing.svelte
Update landing page slogan to a list that will be randomly picked from to keep things fresh
=> Update landing page slogan

internal/http/http.go
Fix swagger docs routing that broke with the OIDC changes to router.
=> Fix swagger docs routing

ui/src/components/global/Pagination.svelte, ui/src/components/table/TableFooter.svelte
Fix pagination from svelte5 upgrade
=> Fix pagination from svelte5 upgrade

ui/src/pages/storyboard/Storyboard.svelte
Resvoles #704 by fixing storyboard collapse expand behavior
=> Resvoles #704 by fixing storyboard collapse expand behavior

internal/db/team/retro.go, internal/db/team/storyboard.go
Fix team removal of storyboard and retro
This resolves #716
=> Fix team removal of storyboard and retro

ui/src/components/global/NavUserMenu.svelte, ui/src/components/user/UserRegisterForm.svelte
=> Enabled guest login along with oidc

internal/db/database.go
This resolves #720
Wait for database to be ready before proceeding with migrations and application startup
This resolves #720
=> Wait for database to be ready

ui/src/i18n/de/index.ts
added missing text in german language file: loginWithSSO
Fixes #727
Steps to test
1. Configure Thunderdome Planning Poker with oidc
2. Configure German language
3. Click the login button (you should see the text now)
=> added text for german loginWithSSO

ui/src/components/poker/CsvImport.svelte
Resolves #730 by supporting commas in csv quoted fields
Resolves #730 by supporting commas in csv quoted fields
=> support commas in csv fields for import

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/db/storyboard/column.go, internal/db/storyboard/goal.go, internal/db/storyboard/story.go, internal/http/checkin.go, internal/http/checkin/checkin.go, internal/http/checkin/client.go, internal/http/checkin/events.go, internal/http/poker.go, internal/http/poker/client.go, internal/http/poker/events.go, internal/http/poker/poker.go, internal/http/retro.go, internal/http/retro/client.go, internal/http/retro/events.go, internal/http/retro/retro.go, internal/http/storyboard.go, internal/http/storyboard/client.go, internal/http/storyboard/events.go, internal/http/storyboard/storyboard.go, internal/http/storyboard_column.go, internal/http/storyboard_goal.go, internal/http/storyboard_story.go, internal/http/types.go, internal/wshub/http.go, internal/wshub/hub.go, internal/wshub/hub_test.go, internal/wshub/subscription.go
This PR  updates the websocket event handlers to return the results of the operation for REST api to return for Storyboard goal, column, and story create events.
Other events will now be easy to update to return values in future PR's.
This resolves #705
=> Update websocket event handlers to return results

ui/src/components/auth/LoginForm.svelte, ui/src/components/forms/Checkbox.svelte, ui/src/components/forms/SelectWithSubtext.svelte, ui/src/components/global/FeatureSubscribeBanner.svelte, ui/src/components/global/MetricsDisplay.svelte, ui/src/components/global/Modal.svelte, ui/src/components/global/SideNavigation.svelte, ui/src/components/poker/InviteUser.svelte, ui/src/components/poker/PokerStories.svelte, ui/src/components/poker/StoryFromGameImport.svelte, ui/src/components/poker/UpdatePokerSettings.svelte, ui/src/components/poker/VotingMetrics.svelte, ui/src/components/retro/InviteUser.svelte, ui/src/components/retro/PhaseTimer.svelte, ui/src/components/retrotemplate/ColumnForm.svelte, ui/src/components/retrotemplate/ViewFormat.svelte, ui/src/components/storyboard/InviteUser.svelte, ui/src/components/storyboard/StoryForm.svelte, ui/src/components/table/TableFooter.svelte, ui/src/components/table/TableNav.svelte, ui/src/components/user/CreateApiKey.svelte, ui/src/components/user/UserRegisterForm.svelte, ui/src/pages/Landing.svelte, ui/src/pages/poker/PokerLanding.svelte, ui/src/pages/retro/RetroLanding.svelte, ui/src/pages/storyboard/StoryboardLanding.svelte
Replace some left/right spacing classes with start/end for further RTL language support.
Also further improve Storyboard Story UX by making labels larger and text sizes consistent.
=> Bugfix rtl ltr spacing

ui/src/pages/storyboard/Storyboard.svelte
This is related to #708 by adding an icon to indicate the story has an external link, future PR will solve for making the link clickable in some way.
=> Add icon for storyboard story link to card

ui/src/components/global/NavUserMenu.svelte, ui/src/components/global/SolidButton.svelte, ui/src/pages/user/Login.svelte
Fix some typescript/vite/svelte build warnings
=> Techdebt typescript warnings fixes

e2e/tests/retro/retro.spec.ts, ui/src/i18n/de/index.ts, ui/src/i18n/en/index.ts, ui/src/i18n/es/index.ts, ui/src/i18n/fa/index.ts, ui/src/i18n/fr/index.ts, ui/src/i18n/i18n-types.ts, ui/src/i18n/it/index.ts, ui/src/i18n/pt/index.ts, ui/src/i18n/ru/index.ts, ui/src/pages/retro/Retro.svelte
Move retro actions to settings button and submenu
Also fix retro headers to use flex instead of fixed percentages
=> Move retro actions to settings button and submenu

ui/src/components/BecomeFacilitator.svelte, ui/src/components/global/Badge.svelte, ui/src/components/poker/PokerStories.svelte, ui/src/components/poker/UserCard.svelte, ui/src/components/storyboard/ActiveUsers.svelte, ui/src/i18n/de/index.ts, ui/src/i18n/en/index.ts, ui/src/i18n/es/index.ts, ui/src/i18n/fa/index.ts, ui/src/i18n/fr/index.ts, ui/src/i18n/i18n-types.ts, ui/src/i18n/it/index.ts, ui/src/i18n/pt/index.ts, ui/src/i18n/ru/index.ts, ui/src/pages/admin/poker/PokerGame.svelte, ui/src/pages/admin/retro/Retro.svelte, ui/src/pages/admin/storyboard/Storyboard.svelte, ui/src/pages/poker/PokerGame.svelte
Update Leader to Facilitator for Poker Games
=> Update Leader to Facilitator for Poker Games

ui/src/i18n/de/index.ts, ui/src/i18n/es/index.ts, ui/src/i18n/fa/index.ts, ui/src/i18n/fr/index.ts, ui/src/i18n/it/index.ts, ui/src/i18n/pt/index.ts, ui/src/i18n/ru/index.ts
Add missing locale keys to non English files
=> Add missing locale keys to non English files

internal/db/migrations/20250813030532_create_project_table.sql
Create Project Schema, start of an entire new feature that will be interconnected to other features in Thunderdome.
=> Create Project Schema

internal/http/poker/poker.go, ui/src/components/global/Badge.svelte, ui/src/components/poker/PokerStories.svelte, ui/src/pages/poker/PokerGame.svelte
Improve poker story drag experience both visually and by locking it down to facilitator only.
=> Improve poker story drag experience

ui/src/components/storyboard/StoryForm.svelte
Fix storyboard story name edit
This resolves #763
=> Fix storyboard story name edit

go.mod, go.sum, internal/atlassian/jira/client.go, internal/atlassian/jira/stories.go, internal/atlassian/jira/types.go
Update Jira cloud library for new apis
This should resolve #773 by using new jira api for JQL search
=> Update Jira cloud library for new apis

ui/src/components/global/HollowButton.svelte, ui/src/components/poker/CsvImport.svelte, ui/src/components/poker/ImportModal.svelte, ui/src/components/poker/JiraImport.svelte
Improve Poker Story Import modal UX, also update HollowButton styles and add fullWidth and size options.
=> Improve Poker Story Import modal UX

ui/src/components/global/SubMenu.svelte, ui/src/components/storyboard/ExportStoryboard.svelte, ui/src/pages/storyboard/Storyboard.svelte, ui/src/types/storyboard.ts
Add export storyboard to xml, csv, json feature with download buttons and copy data buttons in a modal.
This is entirely front-end given the current state of the active storyboard being displayed.
Data exported could likely be improved in XML and CSV formats however its a starting point.
This is related to #431 by adding an easy export of Storyboard to json/xml/csv formats.  Does not include Jira specific output.
=> Add export storyboard to xml, csv, json feature

ui/src/App.svelte
Revert changes to App.svelte to try and fix e2e tests
=> Revert changes to App.svelte to try and fix e2e tests

Taskfile.yml, e2e/global-setup.ts, e2e/global-teardown.ts
Fix some e2e setup for windows support
=> Fix some e2e setup for windows support

ui/src/components/estimationscale/CreateEstimationScale.svelte, ui/src/components/estimationscale/EstimationScalesList.svelte, ui/src/components/estimationscale/UpdateEstimationScale.svelte, ui/src/pages/team/Team.svelte
Fix create estimation scale validation on input
=> Bugfix estimation scales create

ui/src/components/checkin/Checkin.svelte, ui/src/components/checkin/Comment.svelte, ui/src/components/checkin/Comments.svelte, ui/src/components/timezone-picker/Picker.svelte, ui/src/pages/team/TeamCheckin.svelte
This PR improves Team Checkins page UX, as well as upgrades the components to svelte 5 syntax.
=> Improve Team Checkins page UX

ui/public/content/open-source.html, ui/src/App.svelte, ui/src/components/checkin/Comment.svelte, ui/src/components/global/GlobalFooter.svelte, ui/src/config.ts, ui/src/pages/support/OpenSource.svelte, ui/src/pages/team/TeamCheckin.svelte
=> Add an open source page

README.md, Taskfile.yml, cmd/migrate.go, cmd/serve.go, docs/CODE_OF_CONDUCT.md, docs/CONFIGURATION.md, docs/CONTRIBUTING.md, docs/DEVELOPING.md, docs/GUIDE.md, docs/INSTALLATION.md, docs/SECURITY.md, internal/db/database.go, internal/db/migrate.go
This PR adds a new sub-command for running db migrations.
Also updates some documentation files with table of contents, and refreshes the aesthetics of the main README.md
This resolves #791
=> Feat migrate cmd

ui/src/pages/Dashboard.svelte
Fix column heights for dashboard
=> Fix column heights for dashboard

ui/src/pages/Dashboard.svelte, ui/src/validationUtils.ts
Hide teams filter on dashboard for guest users
=> Hide teams filter on dashboard for guest users
