README.md, config.go, docker-compose.yml, go.mod, main.go, pkg/database/database.go, pkg/email/email.go
I've tried implementing issue #43 adding support for using Viper as configuration library.
The changes are backwards compatible, so the environment variables may still be used as before.
I've implemented the config variable lookup as simple calls to viper all over the place.  I'm not sure what your preference is here.  They could certainly also be read into a (bigger) configuration structure at the start to keep the viper calls at one single location.
Let me know what you think.
Oh, I don't really know go, so expect some newbie go errors.
=> Added support for configuration file using Viper

README.md, config.go, frontend/public/index.html, frontend/src/components/CreateBattle.svelte, handlers.go, routes.go
The set of allowed points supported by Thunderdome seems to be quite common, but it really hurts my eyes, as the fibonacci sequence is broken after 13!
So here's a pull request making the list of allowed point values configurable.
I've not used Svelte before, but it seems to work.
I'm not sure about the interface for reading config values over REST, I ended up with a generic interface for request a single config item, and then mapping that item to a viper config.  This way it's easy to control which config values are available over REST.  Another option would be to allow fetching a bigger config structure that contains all frontend related config values.
I'm happy to change the pull request on your request.
=> Make allowed points configurable

frontend/public/index.html
chrome requires crossorigin="use-credentials" to pass cookies (and basic auth) for manifests
=> Fix accessing manifest behind auth on chrome

handlers.go
When updating the warrior's profile an error is shown.
Since UI expects the updated warrior while the handler returns **nil**, an error is shown and changes are not visible to the user.
However, the data in the DB is updated and the changes are available as soon as the cookie is reloaded.
The handler now loads the warrior directly after saving to DB.
This removes the error message and updates the UI as expected.
(VS Code did also some code formatting)
=> Fix error message when updating the profile

README.md, config.go, frontend/src/components/WarriorCard.svelte, frontend/src/pages/WarriorProfile.svelte, handlers.go, pkg/database/battles.go, pkg/database/types.go, pkg/database/warriors.go, schema.sql
Our developers did not like the default avatar service used. So I searched a bit and now we use dicebear. 
With the response from #72 I added a configuration item that allows configuration of different services.
Hope you like it.
From the Readme:
8< ---------------------------------------------
Use the name from table below to configure a service - if not set, `default` is used. Each service provides further options which then can be configured by a warrior on the profile page. Once a service is configured, drop downs with the different sprites get available. The table shows all supported services and their sprites. In all cases the same ID (`ead26688-5148-4f3c-a35d-1b0117b4f2a9`) has been used creating the avatars.
| Name |           |           |           |           |           | …
=> Add different avatar services

README.md, config.go, frontend/src/components/BattlePlans.svelte, frontend/src/components/JiraImport.svelte, frontend/src/pages/Battle.svelte, handlers.go
We use planning poker to evaluate tasks from JIRA. But manual adding plans is laborious. This feature add "Import from JIRA" button. Feature may be enabled by config option and disabled by default. 
JiraImport component render Button and hidden file input. XML parsed with DOMParser.
=> Add import FROM JIRA xml

frontend/src/config.js
Hi. Bug was appeared after [this commit](https://github.com/StevenWeathers/thunderdome-planning-poker/commit/f06e5670e6f8a5be24bf739f5b56e969299e7ee2). In config variable for the registration route called `enlist` but in other files used `appRoutes.register`. So actions related with registration broke.
=> Fix routing for enlist

frontend/public/lang/default/de.json, frontend/public/lang/friendly/de.json, main.go
Found some typos in the German language file and changed some phrases in order not to sound like Google Translator ;-)
Changed the log message that prints the version during startup so it matches the other messages (timestamp as prefix)
=> Fix typos in German language file and change version log message

frontend/src/components/CreateBattle.svelte
When importing Jira tickets on the "create battle" page the links were not stored. This only works when importing plans on the battle page.
I added it as separate PR so it can be merged independent from PR #124.
=> Fix missing link error when importing Jira tickets during battle creation

.gitignore, Makefile, README.md, config.go, frontend/public/lang/default/de.json, frontend/public/lang/default/en.json, frontend/public/lang/default/ru.json, frontend/public/lang/friendly/de.json, frontend/public/lang/friendly/en.json, frontend/public/lang/friendly/ru.json, frontend/src/components/BattlePlans.svelte, frontend/src/components/CreateBattle.svelte, frontend/src/components/JiraImport.svelte, frontend/src/components/JiraImportRest.svelte, frontend/src/components/JiraImportServerData.svelte, frontend/src/pages/Battle.svelte, frontend/src/pages/WarriorProfile.svelte, handlers.go, jira-rest.go, pkg/database/types.go, pkg/database/warriors.go, routes.go, schema.sql
Jira has a great REST API that allows the search for tickets (Stories, Bugs, ...) based on the JQL.
This PR adds the ability to "ask" Jira directly for tickets using the same JQL one would use to export tickets as XML.
By default the feature is disabled since it requires further configuration:
* pre-define the correct server URL (optional, if not set the user must change the dummy on the dialogue)
* Jira limits the amount of tickets in the REST response results to 50 - this can be set to a different value (default is 30)
* The "acceptance criteria" is a custom field in Jira (added by an extension) and needs to be configured here (e.g. as customfield_15023) - otherwise no acceptance criteria will show up
Advantage: I had several issues with the XML export since Jira does not generate error …
=> Use the JIRA REST Api to transfer tickets into Thunderdome

handlers.go, jira-rest.go
Update to the Jira Rest client for #138:
Before adding pagination to the UI it is required to load all tickets for given JQL. Jira Rest API limits the maximum number of tickets returned in one request to 50. The configuration item `JIRA_LIMIT` defines the amount of tickets read in one bundle. The solution iterates the total amount of tickets unless all are loaded.
=> Add pagination to REST call so it returns all tickets from Jira

frontend/public/lang/de.json, frontend/public/lang/default/de.json, frontend/public/lang/default/en.json, frontend/public/lang/default/es.json, frontend/public/lang/default/fr.json, frontend/public/lang/default/pt.json, frontend/public/lang/default/ru.json, frontend/public/lang/en.json, frontend/public/lang/es.json, frontend/public/lang/fr.json, frontend/public/lang/friendly/de.json, frontend/public/lang/friendly/en.json, frontend/public/lang/friendly/es.json, frontend/public/lang/friendly/fr.json, frontend/public/lang/friendly/pt.json, frontend/public/lang/friendly/ru.json, frontend/public/lang/pt.json, frontend/public/lang/ru.json, frontend/src/components/AdminPageLayout.svelte, frontend/src/components/CreateBattle.svelte, frontend/src/components/EditBattle.svelte, frontend/src/i18n.js, frontend/src/pages/Landing.svelte
Basis file (/lang/<locale>.json) contains all items that were identical in default & friendly.
The latter files contain only those values that are different (e.g warrior, battle, ...).
I tested this for locales en & de. If you like this idea I can do the separation also for the rest of the languages and attach them to this PR, too.
Please let me know what you think.
=> Separate the basic translation from the specific (default/friendly)

api/api.go, api/auth.go, api/util.go, config.go, docs/CONFIGURATION.md, frontend/src/components/GlobalHeader.svelte, frontend/src/components/user/ProfileForm.svelte, frontend/src/components/user/UpdatePasswordForm.svelte, frontend/src/pages/UserProfile.svelte, http.go, main.go
My use-case is that I have Thunderdome behind a reverse-proxy (Traefik/HAProxy) which handles authentication for me (In this case I'm using SSL client certs)
The changes here enable Thunderdome to authenticate based on given HTTP headers
The assumption is that Thunderdome is not accessible by any other means aside from the reverse-proxy which also wipes the auth headers to prevent masquerading
I mainly just ctrl+f'd for the LDAP auth code and followed it around. I've confirmed it works with my reverse proxy
Sorry if I missed anything, only my second time touching anything using go 😃
=> Added Header Authentication

frontend/public/lang/pt.json
Accessing the https://thunderdome.dev/ website. When you set 'portuguese' as default language,  when you look to the total of a battle the lable is rendered as 'totalPoints' and not the word 'Total'.
The word 'total' in portuguese has the same meaning as in english.
=> totalPoints key is missing in pt.json lang file

frontend/src/components/GlobalHeader.svelte
=> fix: Failure to Navigate to Teams Page from Navigation Menu on Thunderdome Mobile Website

docs/CONTRIBUTING.md
Fix broken link to Git Flow in the docs contributing file.
Fix issue #476
=> Fix broken link

internal/db/retro/item.go, internal/http/retro/events.go, thunderdome/retro.go, ui/src/pages/retro/Retro.svelte
Also remove reordering of groups during grouping phase as it tends to be jarring and cause too many updates in svelte.
=> Optimize retro group item move and name change socket events

internal/db/poker/poker.go
Fixes #533
This PR fixes a performance issue with getting the list of User Games which when Team Games were added decreased performance drastically for smaller resourced db instances.
Fixes #533
=> Refactor the GetGamesByUser query to improve performance

main.go
This PR fixes the bug regarding the Header Authentication AuthHeaderEmailHeader, as it was not possible to configure a Header name.
- Configure Header Authentication for example:
```
AUTH_METHOD: "header"
AUTH_HEADER_USERNAME_HEADER: "x-token-user-name"
AUTH_HEADER_EMAIL_HEADER: "x-token-user-email"
```
- Now a User can login but the E-Mail field will be empty.
=> Fix header auth, could not configure AuthHeaderEmailHeader

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/db/migrations/20240831211234_add_retro_phase_timebox.sql, internal/db/retro/retro.go, internal/http/retro.go, internal/http/retro/client.go, internal/http/retro/events.go, internal/http/retro/retro.go, thunderdome/retro.go, ui/src/components/retro/CreateRetro.svelte, ui/src/components/retro/EditRetro.svelte, ui/src/components/retro/PhaseTimer.svelte, ui/src/dateUtils.ts, ui/src/i18n/de/index.ts, ui/src/i18n/en/index.ts, ui/src/i18n/es/index.ts, ui/src/i18n/fa/index.ts, ui/src/i18n/fr/index.ts, ui/src/i18n/it/index.ts, ui/src/i18n/pt/index.ts, ui/src/i18n/ru/index.ts, ui/src/pages/retro/Retro.svelte
Add timer to retro feature brainstorm phase
Also adds auto advance phases option that will automatically advance the brainstorm phase when all active users of the retro are marked ready.
This resolves #525 
QA Timer
1. Create a retro and set the time limit in minutes to a number between 1-59 to enable the timer
2. Advance to brainstorm phase
3. Once the timer reaches 0 the brainstorm phase will automatically end and advance
QA Auto Advance
1. Create a retro with auto advance phases enabled
2. Advance to brainstorm phase
3. Mark oneself ready, once all active users of the retro are ready the phase will automatically advance
=> Add timer to retro feature brainstorm phase

e2e/tests/poker-game.spec.ts, internal/db/poker/poker.go, internal/db/retro/retro.go, internal/db/storyboard/storyboard.go, ui/src/components/poker/UserCard.svelte, ui/src/i18n/de/index.ts, ui/src/i18n/en/index.ts, ui/src/i18n/es/index.ts, ui/src/i18n/fa/index.ts, ui/src/i18n/fr/index.ts, ui/src/i18n/it/index.ts, ui/src/i18n/pt/index.ts, ui/src/i18n/ru/index.ts, ui/src/pages/poker/PokerGame.svelte, ui/src/pages/retro/Retro.svelte, ui/src/pages/storyboard/Storyboard.svelte
Add restriction to prevent removal of last facilitator in Poker, Retro, and Storyboard features
Resolves #582 
Attempt to remove last facilitator of a Poker Game, Retro, or Storyboard and you'll get an error notification stating you can't remove the last facilitator.
=> Add restriction to prevent removal of last facilitator

docs/swagger/docs.go, docs/swagger/swagger.json, docs/swagger/swagger.yaml, internal/db/migrations/20240913020848_add_retro_vote_stacking.sql, internal/db/poker/poker.go, internal/db/retro/item.go, internal/db/retro/retro.go, internal/db/retro/vote.go, internal/db/team/team.go, internal/http/http.go, internal/http/retro.go, internal/http/team.go, thunderdome/retro.go, thunderdome/team.go, ui/src/components/retro/CreateRetro.svelte, ui/src/components/retro/GroupedItems.svelte, ui/src/components/retro/UserCard.svelte, ui/src/components/retro/VotePhase.svelte, ui/src/i18n/de/index.ts, ui/src/i18n/en/index.ts, ui/src/i18n/es/index.ts, ui/src/i18n/fa/index.ts, ui/src/i18n/fr/index.ts, ui/src/i18n/it/index.ts, ui/src/i18n/pt/index.ts, ui/src/i18n/ru/index.ts, ui/src/pages/retro/Retro.svelte, ui/src/pages/team/Teams.svelte
This PR adds cumulative voting option to retros (defaulting to false) allowing users to vote more than once on an item group.
This resolves #614
=> Add cumulative voting option to retros defaulting to false

internal/fracindex/example_test.go, internal/fracindex/fracindex.go, internal/fracindex/fracindex_test.go
This PR adds a new internal lib for fractional indexing (using base95 characters) to support upcoming sort features for Storyboard as well as future features.
=> Add lib for fractional indexing

go.mod, go.sum
This PR updates the go-mail dependency from v0.5.0 to v0.5.1 to fix a bug:
* The issue: https://github.com/wneessen/go-mail/issues/332
* The PR: https://github.com/wneessen/go-mail/pull/335
In few words, with go-mail v0.5.0, we can't use the SMTP client without authentification.
In my case, my SMTP server doesn't support authentification (I know, it's bad), but the library always check if it does and crash if it doesn't, even when I configure the SMTP client to don't use any kind of authentification (authentification type not set or set to "NOAUTH" for example).
This bug is now solved in the go-mail library so just updating it to the last availavble version (v0.5.1 for the moment) would fix this.
Current error logs with no auth method:
``` …
```
=> fix: SMTP no auth support

ui/src/components/poker/PokerStories.svelte
This PR replaces the style of the Poker Stories page to ensure the alignment of action buttons on each line of the story list, as illustrated in the attached screenshot.
Details:
- Enhances visual consistency by aligning buttons across all rows.
- Optimizes the use of available space, providing more width pixels for story text.
Basically, these changes improve both the aesthetics and readability of the page.
=> style: poker stories plans text and buttons align

.github/workflows/build.yml, .github/workflows/lint.yml, build/Dockerfile, ui/package-lock.json
Upgrade to node 22 from 20 for build life maintenance
=> Upgrade to node 22 from 20 for build life maintenance

internal/http/http.go
This PR fixes the CSP directive for `default-src`, which used to contain `self` (note the lack of quotes) which gets interpreted by browsers as the _hostname_ `self`. By adding quotes (`'self'`), this is fixed.
I believe the lack of quotes caused the user's selected theme not to be applied (but I'm not quite sure _why_, as the `<script>` adding the theme's class has a `nonce`).
Additionally, the `connect-src` CSP directive used to _always_ include Google Analytics, even with analytics disabled. This PR also omits the Google Analytics hosts when analytics is disabled.
=> CSP fix + omit Google Analytics if analytics is disabled.

internal/db/auth/oauth.go
This PR attempts to fix #679 by upserting user based on email not sub when falling back to existing users. 
Likely a fix for #679
=> Fix oidc flow upsert for user, sub doesnt always match email

internal/email/email.go, internal/email/util.go, internal/email/util_test.go
Add removal of accents in username for email address TO header.
Also add error handling on invalid address headers instead of ignoring them and attempting to send.
#662 potentially fixes this issue if the username containing accents is the root cause
=> Add removal of accents in username for email address TO header

ui/src/components/global/Modal.svelte
Resolves #698 by adding an escape key handler to modals allowing quick closure via keyboard
=> Resolves #698 by adding an escape key handler to modals

internal/http/http.go
Resolves #709 by fixing the http method of the endpoint back to POST
=> Resolves #709 by fixing the http method of the endpoint back to POST

ui/src/components/global/NavUserMenu.svelte
This will resolve the scenario where a users selected avatar type isn't being passed in for the header avatar.
Related to #731 however there is a second part to that issue still being questioned so not closing for now.
=> Add avatar field from profile to header avatar invoction

ui/src/components/poker/PokerStories.svelte
Added drag and drop feature.
Added additional icon to see that drag and drop is available.
Fixes #756
https://github.com/user-attachments/assets/6a1feeea-1672-49e8-896e-28cee6b65fe5
Please provide some steps for the reviewer to test your change. If you have written tests, you can mention that here instead.
1. Drag a story in game view
2. Drop it on the position you want it to be
3. Do the same in "pointed", "unpointed" and "all" tab
-->
=> added drag and drop feature for stories

internal/db/team/team.go
This PR should fix a minor bug highlighted by issue #770 that isn't necessarily the issue in the storyboard itself but none the less can cause unnecessary errors.
=> Fix possible left join bug on TeamListByUser db method

ui/src/components/retro/RetroFeedbackGroup.svelte, ui/src/components/retro/VotePhase.svelte, ui/src/pages/retro/Retro.svelte, ui/src/types/retro.ts
Improved UX of Retro item group voting for both cumulative and non cumulative voting styles.
Replaced single button voting action with down/up to clearly guide user in changing votes.
Added messaging around vote counts per group and overall limits.
Alerting user when they've reached their max votes and that they can remove votes.
This resolves #758 by providing a better User Experience for cumulative and non cumulative voting.
=> Improved UX of Retro item group voting

ui/src/components/poker/PokerStories.svelte, ui/src/components/poker/UserCard.svelte, ui/src/pages/poker/PokerGame.svelte
This PR updates Poker Game UI for Game Over scenario.
Once the game is ended the poker game UI hides story actions and voting controls.
=> Update Poker Game UI for Game Over

ui/src/App.svelte, ui/src/components/team/TeamPageLayout.svelte, ui/src/pages/team/Team.svelte, ui/src/pages/team/TeamProjects.svelte, ui/src/pages/team/TeamUsers.svelte
This PR fixes a bug with the new team page side navigation links which were not going to the right page so that team admin permissions reflected on the users management page.
=> Fix Org and Dept team users page routes
